type:
  yml

http_server:
  port: 8080

matching_service:
  waiting_timeout: '3m'

mysql:
  port: 3308
  host: localhost
  db_name: gameapp_db
  username: gameapp
  password: gameappt0lk2o20

redis:
  port: 6380
  host: localhost
  db: 0
  password:

presence_service:
  expiration_time: "60m"
  prefix: "presence"

scheduler:
  match_waited_users_interval_in_seconds: "30"